import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const localeDir = path.join(root, 'src', 'locales');
const outFile = path.join(root, 'src', 'locales', 'bundles.ts');
const langs = fs.readdirSync(localeDir).filter((entry) => fs.statSync(path.join(localeDir, entry)).isDirectory());
const bundles = {};
for (const lang of langs) {
  bundles[lang] = {};
  for (const file of fs.readdirSync(path.join(localeDir, lang)).filter((name) => name.endsWith('.json')).sort()) {
    const namespace = path.basename(file, '.json');
    const data = JSON.parse(fs.readFileSync(path.join(localeDir, lang, file), 'utf8'));
    bundles[lang][namespace] = data;
  }
}
const body = `// This file is generated by scripts/generate-locales.mjs. Do not edit manually.
export const localeBundles = ${JSON.stringify(bundles, null, 2)} as const;
export type LocaleCode = keyof typeof localeBundles;
`;
fs.writeFileSync(outFile, body, 'utf8');
console.log(`generated ${path.relative(root, outFile)}`);
