export type AssetKey = keyof typeof assetRegistry;
const base = '/assets/BandKit_Production_Assets_v1_3/';

export const assetRegistry = {
  logoPrimary: `${base}brand/svg/logo-primary.svg`,
  logoLight: `${base}brand/svg/logo-light.svg`,
  mark: `${base}brand/svg/mark.svg`,
  markTile: `${base}brand/svg/mark-tile.svg`,
  navFeedActive: `${base}navigation/active/svg/feed.svg`,
  navFeedInactive: `${base}navigation/inactive/svg/feed.svg`,
  navSearchActive: `${base}navigation/active/svg/search.svg`,
  navSearchInactive: `${base}navigation/inactive/svg/search.svg`,
  navProjectsActive: `${base}navigation/active/svg/projects.svg`,
  navProjectsInactive: `${base}navigation/inactive/svg/projects.svg`,
  navEventsActive: `${base}navigation/active/svg/events.svg`,
  navEventsInactive: `${base}navigation/inactive/svg/events.svg`,
  navChatsActive: `${base}navigation/active/svg/chats.svg`,
  navChatsInactive: `${base}navigation/inactive/svg/chats.svg`,
  navFilesActive: `${base}navigation/active/svg/files.svg`,
  navFilesInactive: `${base}navigation/inactive/svg/files.svg`,
  navNotificationsActive: `${base}navigation/active/svg/notifications.svg`,
  navNotificationsInactive: `${base}navigation/inactive/svg/notifications.svg`,
  navSettingsActive: `${base}navigation/active/svg/settings.svg`,
  navSettingsInactive: `${base}navigation/inactive/svg/settings.svg`,
  navAdminActive: `${base}navigation/active/svg/admin.svg`,
  navAdminInactive: `${base}navigation/inactive/svg/admin.svg`,
  navRatingInactive: `${base}navigation/inactive/svg/rating.svg`,
  navMusiciansInactive: `${base}navigation/inactive/svg/musicians.svg`,
  badgeVerified: `${base}badges/active/svg/verified.svg`,
  badgeTrusted: `${base}badges/active/svg/trusted.svg`,
  badgeWarning: `${base}badges/active/svg/warning.svg`,
  badgeRestricted: `${base}badges/active/svg/restricted.svg`,
  badgeEmail: `${base}badges/active/svg/email_verified.svg`,
  badgePhone: `${base}badges/active/svg/phone_verified.svg`,
  badgeTwoFactor: `${base}badges/active/svg/two_factor.svg`,
  avatarMusician: `${base}fallbacks/avatars/svg/user_musician.svg`,
  avatarGuitarist: `${base}fallbacks/avatars/svg/guitarist.svg`,
  avatarVocalist: `${base}fallbacks/avatars/svg/vocalist.svg`,
  avatarSound: `${base}fallbacks/avatars/svg/sound_engineer.svg`,
  coverProfile: `${base}fallbacks/covers/svg/user_profile.svg`,
  coverBand: `${base}fallbacks/covers/svg/band_project.svg`,
  coverOrchestra: `${base}fallbacks/covers/svg/orchestra.svg`,
  coverStudio: `${base}fallbacks/covers/svg/studio.svg`,
  coverConcert: `${base}fallbacks/covers/svg/concert.svg`,
  coverRehearsal: `${base}fallbacks/covers/svg/rehearsal.svg`,
  coverVenue: `${base}fallbacks/covers/svg/venue.svg`,
  coverEvent: `${base}fallbacks/covers/svg/event.svg`,
  coverChat: `${base}fallbacks/covers/svg/chat.svg`,
  coverDocument: `${base}fallbacks/covers/svg/document.svg`,
  emptyPosts: `${base}empty-states/svg/no_posts.svg`,
  emptyMessages: `${base}empty-states/svg/no_messages.svg`,
  emptyFiles: `${base}empty-states/svg/no_files.svg`,
  emptyEvents: `${base}empty-states/svg/no_events.svg`,
  emptyNoAccess: `${base}empty-states/svg/no_access.svg`,
  emptyRestricted: `${base}empty-states/svg/account_restricted.svg`,
  emptyVerification: `${base}empty-states/svg/verification_required.svg`,
  illustrationPortfolio: `${base}feature-illustrations/svg/portfolio.svg`,
  illustrationChats: `${base}feature-illustrations/svg/chats.svg`,
  illustrationCalendar: `${base}feature-illustrations/svg/calendar.svg`,
  illustrationSecurity: `${base}feature-illustrations/svg/security_center.svg`,
  docRider: `${base}documents/active/svg/rider.svg`,
  docContract: `${base}documents/active/svg/contract.svg`,
  docSetlist: `${base}documents/active/svg/setlist.svg`,
  docPdf: `${base}documents/active/svg/pdf.svg`,
  roleMusician: `${base}roles/active/svg/musician.svg`,
  roleGroup: `${base}roles/active/svg/group.svg`,
  roleProject: `${base}roles/active/svg/project.svg`,
  roleDrummer: `${base}roles/active/svg/drummer.svg`,
  roleSoundEngineer: `${base}roles/active/svg/sound_engineer.svg`,
  roleStudio: `${base}roles/active/svg/studio.svg`,
  roleManager: `${base}roles/active/svg/manager.svg`,
} as const;

export function getAsset(key: AssetKey): string {
  return assetRegistry[key];
}
